# Generated by Django 5.1.3 on 2024-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_event_recurring_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='one_day_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia'),
        ),
    ]
