# Generated by Django 5.1.3 on 2024-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_event_end_date_alter_event_one_day_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='added_by',
            field=models.CharField(choices=[('organizer', 'Organizatora'), ('participant', 'Uczestnika')], default='organizer', max_length=20, verbose_name='Dodane przez'),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_type',
            field=models.CharField(choices=[('free', 'Wolny'), ('paid', 'Płatny')], default='free', max_length=20, verbose_name='Wstęp'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('inside', 'Wewnątrz'), ('outside', 'Na zewnątrz')], default='inside', max_length=20, verbose_name='Gdzie'),
        ),
    ]
