# Generated by Django 5.1.3 on 2024-12-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_event_added_by_alter_event_entry_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_one_day',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('one_day', 'Jednodniowe'), ('multi_day', 'Kilkudniowe'), ('recurring', 'Cykliczne')], default='one_day', max_length=20, verbose_name='Rodzaj wydarzenia'),
        ),
    ]
