# Generated by Django 5.1.3 on 2024-12-13 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_event_is_one_day_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/events/gallery_images/', verbose_name='Zdjęcie galerii 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/events/gallery_images/', verbose_name='Zdjęcie galerii 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/events/gallery_images/', verbose_name='Zdjęcie galerii 3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/events/gallery_images/', verbose_name='Zdjęcie galerii 4'),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='web.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uczestnik',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
