# Generated by Django 5.1.3 on 2024-12-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_activatetoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='veryfication_code',
            new_name='verification_code',
        ),
    ]
