# Generated by Django 5.1.3 on 2024-12-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_eventlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbs')),
                ('mimetype', models.CharField(max_length=16, verbose_name='Typ pliku')),
                ('width', models.IntegerField(default=0, verbose_name='Szerokość')),
                ('height', models.IntegerField(default=0, verbose_name='Wysokość')),
                ('image_type', models.IntegerField(choices=[(1, 'Zdjęcie głowne'), (2, 'Galeria 1'), (3, 'Galeria 2'), (4, 'Galeria 3'), (5, 'Galeria 4')], db_index=True, verbose_name='Rodzaj zdjęcia')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.event', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Thumbnails',
                'ordering': ('-id',),
            },
        ),
    ]
