# Generated by Django 5.1.3 on 2024-12-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnails_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
