# Generated by Django 5.1.3 on 2024-12-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_event_thumbnails_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywne'),
        ),
        migrations.AlterField(
            model_name='event',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numer domu wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Kod pocztowy wydarzenia'),
        ),
    ]
